[shell]
program = "/usr/local/bin/zellij"
args = ["-l", "welcome"]

[window]
decorations = "None"
resize_increments = true
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "T", mods = "Command", action = "ReceiveChar" },
  { key = "]", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "[", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "Tab", mods = "Command", action = "ReceiveChar" },
  { key = "Tab", mods = "Command|Shift", action = "ReceiveChar" },
  { key = "1", mods = "Command", action = "ReceiveChar" },
  { key = "2", mods = "Command", action = "ReceiveChar" },
  { key = "3", mods = "Command", action = "ReceiveChar" },
  { key = "4", mods = "Command", action = "ReceiveChar" },
  { key = "5", mods = "Command", action = "ReceiveChar" },
  { key = "6", mods = "Command", action = "ReceiveChar" },
  { key = "7", mods = "Command", action = "ReceiveChar" },
  { key = "8", mods = "Command", action = "ReceiveChar" },
  { key = "9", mods = "Command", action = "ReceiveChar" },
]

# KDE Breeze (Ported from Konsole)
[colors.primary]
background = '#232627'
foreground = '#fcfcfc'

dim_foreground = '#eff0f1'
bright_foreground = '#ffffff'

[colors.normal]
black = '#232627'
red = '#ed1515'
green = '#11d116'
yellow = '#f67400'
blue = '#1d99f3'
magenta = '#9b59b6'
cyan = '#1abc9c'
white = '#fcfcfc'

[colors.bright]
black = '#7f8c8d'
red = '#c0392b'
green = '#1cdc9a'
yellow = '#fdbc4b'
blue = '#3daee9'
magenta = '#8e44ad'
cyan = '#16a085'
white = '#ffffff'

[colors.dim]
black = '#31363b'
red = '#783228'
green = '#17a262'
yellow = '#b65619'
blue = '#1b668f'
magenta = '#614a73'
cyan = '#186c60'
white = '#63686d'
